services:
  app:
    build:
      context: ../../
      dockerfile: utils/docker_env/Dockerfile.standalone
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../../:/app